---
title: "linear_models"
output: github_document
date: "2022-11-10"
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(viridis)

set.seed(1)

knitr::opts_chunk$set(echo = TRUE)
```


```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) %>% 
  filter(borough != "Staten Island") %>% 
  select(price, stars, borough, neighborhood, room_type)
```

# Fit the first model
```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)

summary(fit)

fit %>% 
  broom::tidy() %>% 
  mutate(term = str_replace(term, "^borough", "Borough: ")) %>% 
  select(term, estimate, p.value) %>% 
  knitr::kable(digits = 2)
```

# Let's change reference group
```{r}
fit = 
  nyc_airbnb %>% 
  mutate(borough = fct_infreq(borough)) %>% 
  lm(price ~ stars + borough, data = .)

fit %>% 
  broom::tidy() %>% 
  mutate(term = str_replace(term, "^borough", "Borough: ")) %>% 
  select(term, estimate, p.value) %>% 
  knitr::kable(digits = 2)

fit %>% 
  broom::glance()

```




